require('dotenv').config();

const {
  POLYGON_API_KEY,
  FINNHUB_API_KEY,
  NEWSAPI_KEY,
  DISCORD_WEBHOOK_URL,
  TELEGRAM_BOT_TOKEN,
  TELEGRAM_CHAT_ID,
  SLACK_WEBHOOK_URL,
  CHATGPT_API_KEY,
  TIINGO_API_KEY,
  CRYPTO_PANICK_API_KEY,
  MARKETEUX_API_KEY,
  ALPHA_VANTAGE_API_KEY,
  PRICE_MOVEMENT_THRESHOLD,
  TREND_THRESHOLD,
  TREND_WINDOW_HOURS,
  POLL_INTERVAL,
  STORAGE_INTERVAL,
  GOOGLE_CLOUD_PROJECT_ID,
  GOOGLE_CLOUD_ACCESS_TOKEN,
} = process.env;

module.exports = {
  polygonApiKey: POLYGON_API_KEY,
  finnhubApiKey: FINNHUB_API_KEY,
  newsApiKey: NEWSAPI_KEY,
  discordWebhookUrl: DISCORD_WEBHOOK_URL,
  telegramBotToken: TELEGRAM_BOT_TOKEN,
  // Chat ID for Telegram notifications
  telegramChatId: TELEGRAM_CHAT_ID,
  slackWebhookUrl: SLACK_WEBHOOK_URL,
  chatGPTApiKey: CHATGPT_API_KEY,
  tiingoApiKey: TIINGO_API_KEY,
  cryptoPanickApiKey: CRYPTO_PANICK_API_KEY,
  marketeuxApiKey: MARKETEUX_API_KEY,
  alphaVantageApiKey: ALPHA_VANTAGE_API_KEY,
  priceMovementThreshold: parseFloat(PRICE_MOVEMENT_THRESHOLD) || 5,
  trendThreshold: parseFloat(TREND_THRESHOLD) || 10,
  trendWindowHours: parseInt(TREND_WINDOW_HOURS) || 24,
  pollInterval: parseInt(POLL_INTERVAL) || 60000,
  storageInterval: parseInt(STORAGE_INTERVAL) || 300000,
  googleCloudProjectId: GOOGLE_CLOUD_PROJECT_ID,
  googleCloudAccessToken: GOOGLE_CLOUD_ACCESS_TOKEN,
};
